### ISSUE TITLE
Lambda: create a Dockerfile that can run as a Lambda function

### ISSUE THREAD

**Issue by patheard** [cds-snc/simplify-privacy-statements-V2#215]
## Description
Currently the app runs in Heroku using the Node `http` module:

- [Server create and listen](https://github.com/cds-snc/simplify-privacy-statements-V2/blob/2af234768e1133ab808d7663b7b4d0ec19222379/bin/www#L80-L88)

We need to wrap calls to the server so that the Lambda invocation events are converted into an HTTP request that the Node `http` server understands how to process.  We should be able to use the [`serverless-http` module](https://www.npmjs.com/package/serverless-http) to make this happen.

## Todo
- [x] Create a Dockerfile for the Lambda.  Notify's Admin PR review environment has a [Python example of this](https://github.com/cds-snc/notification-admin/blob/main/ci/Dockerfile.lambda).  The AWS docs also have good info on how to create a [Node.js Docker image based Lambda function](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-image.html).
- [x] Alter the app's code so that the `serverless-http` module wraps calls to the Node `http` server.
- [x] Test 🧪  You can either follow [AWS's localhost testing docs](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html) or create and test the Lambda function + function URL in your Scratch account.

## Related
- #207

**Comment by omartehsin1** [comment]
- At the moment just testing out creating a Dockerfile for the Lambda Functional URL to behave as a website. Testing it out on a basic hello-world application before moving to simplify privacy statements
- Right now trying to get a better grasp of Docker

Plans for next week:
- Hopefully have the basic app running before moving to the simplify privacy statement
- Get a better understanding of Lambda Functions

**Comment by omartehsin1** [comment]
This week:
- Making progress with Lambda and Docker, able to have the Dockerfile for the lambda function, it is able to run as a website. The part that I am stuck on is it being able to generate the word doc -> always leads to an error.
- Continuing to do research on this issue

Next week:
- Continue to learn more about Docker and Terraform.

**Comment by omartehsin1** [comment]
This week:
- Still trying to figure out the nodePandoc issue, having some trouble with downloading the file
- Looking into other AWS resources, specifically EFS to see if it will help us

**Comment by omartehsin1** [comment]
Completed

- Created a Lambda container image that behaves like a website. 
- Using `serverless-http` module to wrap calls to the Node `http` server
- The biggest hurdle was being able to use `node-pandoc` to convert then download the file. The issue was:
1.) Lambda timed out before the response could be processed so we increased the timeout to give pandoc time to generate the file
2.) Send the html response in the nodepandoc callback to give pandoc the time it needed to generate the file. lambda will only be terminated once it send the response
3.) let `serverless-http` know that is should base64 the docx files before streaming the response.
